version: '3'
services:
  dev:
    build: .
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - .:/usr/src/app
    tty: true
    entrypoint: /bin/bash
    ports:
      - '8001:8001'
